@startuml

'entities'

''!$Prs = "Person"
!$Req = "Request"
!$Evn = "Event"
!$Cst = "Customer"
''!$Pmn = "Payment"
!$Bl = "Bill"
''!$Sl = "Sale"
!$Rl = "Role"
!$Rst = "Requisite"
!$Hst = "Host"
!$Sch = "Schedule"
!$Acd = "Accident"
!$Rep = "Report"
!$Acc = "Account"
!$Prc = "Price"

!$Lst = "List"
!$HstLst = $Hst+$Lst
!$PrcLst = $Prc+$Lst

!$ReqRep = $Req+$Rep
!$EvnRep = $Evn+$Rep
!$SchRep = $Sch+$Rep
!$RstRep = $Rst+$Rep

'Actors'
!$Op = "Operator"
!$Mn = "Manager"
!$Adm = "Administrator"

'methods'
!$reg = "register"
!$gt = "get"
!$cr = "create"
!$dl = "delete"
!$rd = "read"
!$up = "update"
!$acc = "accept"
!$mn = "manage"
!$us = "use"


@enduml
